name: janux
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - paramiko     # For SSH connections
  - typer        # For command-line interface
  - pyyaml       # For configuration parsing
  - cryptography # For key management