name: janux
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # Specific functionality
  - typer        # For command-line interface
  - pyyaml       # For configuration parsing
  - paramiko     # For SSH connections
  - cryptography # For key management
  # Development tools
  - black                  # code formatting
  - mypy                   # static type checking
  - mypy_extensions
  - pylint                 # code linting
  - pyright                # code linting
  # Testing
  - pytest
  - pytest-mock
  - pytest-cov
  - pytest-pylint          # Pylint plugin for Pytest
  # Documentation
  - sphinx                 # documentation generator
  - myst-parser            # Markdown support for Sphinx
  - sphinxcontrib-napoleon # for numpydoc-style docstrings
  - sphinx-rtd-theme       # ReadTheDocs theme
  - sphinx-needs           # for requirements and specifications in Sphinx
  - esbonio                # language server for Sphinx
  # CLI
  - rich
